# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='genre',
            new_name='organization_type',
        ),
    ]
